### ISSUE TITLE
Put dockerfile on dockerhub

### ISSUE THREAD

**Issue by ghost** [Flood-UI/flood#732] opened 2018-10-14 22:44 UTC
Type: Feature Request

- [x] If you want to contribute to the project please review the [contributing guidelines](https://github.com/jfurrow/flood/blob/master/.github/CONTRIBUTING.md).

## Summary

Having the dockerfile published to dockerhub (for free!) is very useful in the docker community. it opens up many possibilities, including using docker-compose and not having to manually create it on the cli.

## Idea of implementation

Make a dockerhub account and link it to github and build a new docker container on every push to master. It will take someone 15minutes or less.

**Comment by noraj** [comment] 2018-10-14 22:47
Hi @robertbaker 

Thanks for posting your issue, but can you please take time to edit it in order to fill the issue template.

```markdown
---
name: "💡 Feature Request"
about: "Suggest an idea for this project"
---
Type: Feature Request

- [ ] If you want to contribute to the project please review the [contributing guidelines](https://github.com/jfurrow/flood/blob/master/.github/CONTRIBUTING.md).

## Summary

<!--- Provide a general summary of the feature in the Title above -->

## Idea of implementation

<!--- Suggest ideas how to implement the addition or change -->
```

I'm closing the issue until you fill it. 

Feel free to ask to re-open it as soon as it's done.

**Comment by robertbaker** [comment] 2018-10-14 22:54
@noraj please reopen.

**Comment by bbashy** [comment] 2018-10-15 10:10
There is this https://hub.docker.com/r/wonderfall/rtorrent-flood/ but I think Flood isn't something that should be rebuilt after every change. You'd pull it in via git and build it yourself through commands.

**Comment by http403** [comment] 2018-10-17 02:34
There's a 1:1 [auto updated docker build](https://hub.docker.com/r/themetabay/flood/) that I'm using for my seedbox build. However I don't think flood shouldn't be updated for every change as it might break something, security patch is an exception though.

**Comment by robertbaker** [comment] 2018-10-17 04:04
Latest should be develop, tag the releases with a version number. Just need
the discipline to use feature branches.

**Comment by robertbaker** [comment] 2018-10-17 07:14
I can't find a rtorrent docker container with XMLRPC enabled that can talk to flood/sonarr/radarr.

**Comment by http403** [comment] 2018-10-17 20:34
@robertbaker https://hub.docker.com/r/https403/docker-rtorrent/ this might help

**Comment by penx** [comment] 2018-11-07 22:12
Duplicate of #448 lmfao roflcopter

**Comment by noraj** [comment] 2019-08-16 15:17
closed as duplicate of https://github.com/Flood-UI/flood/issues/448

**Closed by noraj** 2019-08-16 15:17 UTC
Labels: docker, duplicate
